version: "3.2"
services:
  redis:
    image: redis
    volumes: 
      - ./data:/data
  broker:
    volumes:
        - ./broker/:/mnt/
    build: ./broker
    working_dir: /broker/
    command: sh run_broker.sh
    depends_on: 
      - redis
  receptor:
    volumes:
        - ./receptor/:/mnt/
    build: ./receptor
    working_dir: /receptor/
    command: sh run_receptor.sh
  monitor:
    volumes:
        - ./monitor/:/mnt/
    build: ./monitor
    working_dir: /monitor/
    command: sh run_monitor.sh
  llamadas_principal:
    volumes:
        - ./llamadas/llamadas_principal/:/mnt/
    build: ./llamadas/llamadas_principal
    working_dir: /llamadas/llamadas_principal/
    command: sh run_llamadas_principal.sh

  llamadas_redundante:
    volumes:
      - ./llamadas/llamadas_redundante/:/mnt/
    build: ./llamadas/llamadas_redundante
    working_dir: /llamadas/llamadas_redundante/
    command: sh run_llamadas_redundante.sh