version: "3.2"
services:
  redis:
    image: redis
    volumes:
      - ./data:/data
      - ./nginx/tls/redis-cert.pem:/etc/redis/tls/redis-cert.pem:ro
      - ./nginx/tls/llave.pem:/etc/redis/tls/llave.pem:ro
      - ./nginx/tls/ca-cert.pem:/etc/redis/tls/ca-cert.pem:ro 
      - ./broker/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  broker:
    volumes:
        - ./broker/:/mnt/
        - ./nginx/tls/broker-cert.pem:/etc/broker/tls/broker-cert.pem:ro
        - ./nginx/tls/llave.pem:/etc/broker/tls/llave.pem:ro
        - ./nginx/tls/ca-cert.pem:/etc/broker/tls/ca-cert.pem:ro
    build: ./broker
    working_dir: /broker/
    command: sh run_broker.sh
    depends_on: 
      - redis
  receptor:
    volumes:
        - ./receptor/:/mnt/
    build: ./receptor
    working_dir: /receptor/
    command: sh run_receptor.sh
    depends_on:
      - redis
  monitor:
    build: ./monitor
    working_dir: /monitor/
    command: sh run_monitor.sh
    depends_on:
      - redis
  llamadas-queries:
    volumes:
      - ./llamada/:/mnt/
      - ./nginx/tls/certificado.pem:/etc/llamada/tls/certificado.pem:ro
      - ./nginx/tls/llave.pem:/etc/llamada/tls/llave.pem:ro
      - ./nginx/tls/ca-cert.pem:/etc/llamada/tls/ca-cert.pem:ro 
    build: ./llamada
    working_dir: /backend/
    command: sh run_queries.sh
    depends_on: 
      - redis
    ports:
    - "5001:5001"
  
  nginx:
    image: nginx:latest
    ports:
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/tls/certificado.pem:/etc/nginx/tls/certificado.pem:ro
      - ./nginx/tls/llave.pem:/etc/nginx/tls/llave.pem:ro
      - ./nginx/tls/ca-cert.pem:/etc/nginx/tls/ca-cert.pem:ro
      - ./nginx/tls/broker-cert.pem:/etc/nginx/tls/broker-cert.pem:ro
      - ./nginx/tls/autorizador-cert.pem:/etc/nginx/tls/autorizador-cert.pem:ro
    depends_on:
        - llamadas-queries
  
  autorizador:
    volumes:
      - ./autorizador/:/mnt/
      - ./nginx/tls/autorizador-cert.pem:/etc/autorizador/tls/autorizador-cert.pem:ro
      - ./nginx/tls/llave.pem:/etc/autorizador/tls/llave.pem:ro
      - ./nginx/tls/ca-cert.pem:/etc/autorizador/tls/ca-cert.pem:ro 
    build: ./autorizador
    working_dir: /autorizador/
    command: sh run_autorizador.sh
    ports:
      - "5005:5005"
    
  api-gateway:
    volumes:
      - ./api-gateway/:/mnt/
      - ./nginx/tls/api-gateway-cert.pem:/etc/api-gateway/tls/api-gateway-cert.pem:ro
      - ./nginx/tls/llave.pem:/etc/api-gateway/tls/llave.pem:ro
      - ./nginx/tls/ca-cert.pem:/etc/api-gateway/tls/ca-cert.pem:ro
      - ./nginx/tls/api-comandos-cert.pem:/etc/api-gateway/tls/api-comandos-cert.pem:ro
    build: ./api-gateway
    working_dir: /api-gateway/
    command: sh run_api_gateway.sh
    ports:
      - "6000:6000"
  
  api-comandos:
    volumes:
      - ./api-comandos/:/mnt/
      - ./nginx/tls/api-comandos-cert.pem:/etc/comandos/tls/api-comandos-cert.pem:ro
      - ./nginx/tls/llave.pem:/etc/comandos/tls/llave.pem:ro
      - ./nginx/tls/ca-cert.pem:/etc/comandos/tls/ca-cert.pem:ro 
    build: ./api-comandos
    working_dir: /api-comandos/
    command: sh run_api_comandos.sh
    ports:
      - "5003:5003"
